version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test
    volumes:
      - pg_vol:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 80:8080

volumes:
  pg_vol: