version: '3'
services:
  database:
    image: postgres:14
    environment:
      POSTGRES_DB: todo_list
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - vol_db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready",  "-U", "admin"]
  create-table:
    image: postgres:14
    command: bash -c 'PGPASSWORD=admin psql -U admin --dbname todo_list -p 5432 -h database -c "CREATE TABLE IF NOT EXISTS user_table (user_id int PRIMARY KEY, username varchar(256), email varchar(256));"'
    depends_on:
      database:
        condition: service_healthy
volumes:
  vol_db: